import {withPageAuthRequired} from "@auth0/nextjs-auth0"
import Head from "next/head"
import {useEffect} from "react"
import {getNeighborhoods} from "../src/GetNeighborhoods"
import useUserData from "../src/UseUserData"
import styles from "../styles/Home.module.css"
import { Navbar } from "./components";

export default function Home({neighborhoods}: { neighborhoods: ReadonlyArray<any> }) {

	const user = useUserData()

	useEffect(() => {
		console.log("este log se ejecuta en el browser")
	}, [])

	console.log("este log se ejecuta en el server")

	return (
		<>
			<Navbar nickname={user.nickname}/>
			<div className={styles.container}>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app"/>
					<link rel="icon" href="/favicon.ico"/>
				</Head>

				<main className={styles.main}>
					<span>{"email: " + user.email}</span>
					<span>{"is admin? " + user.isAdmin}</span>
					<span>{"is auditor? " + user.isAuditor}</span>
					<span>{"is proprietor? " + user.isProprietor}</span>

					<button onClick={createNeighborhood}>CREATE NEW NEIGHBORHOOD</button>

					{neighborhoods.map(neighborhood =>
						<button onClick={() => deleteNeighborhoodOfId(neighborhood.id)}>{neighborhood.name}</button>
					)}
				</main>
			</div>
		</>
	)
}

export const getServerSideProps = withPageAuthRequired({
	getServerSideProps: async () => {
		const neighborhoods = await getNeighborhoods()
		return {props: {neighborhoods}}
	}
})

async function createNeighborhood() {
	await fetch(`/api/neighborhoods`, { method: "POST" })
}

async function deleteNeighborhoodOfId(id: string) {
	await fetch(`/api/neighborhoods/${id}`, { method: "DELETE" })
}